#  DISOCCUPATION DIAGNOSTIC EXPLORATION
In this notebook I am proceeding to conduct a diagnostic analysis of the DISOCCUPATION dataset and preparing it for next analysis.

In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
DISOCCUPATION_FOR_NATION_path= Path.cwd().parent/"data/raw_data/disoccupation_for_nation.csv"

In [ ]:
DISOCCUPATION_FOR_NATION= pd.read_csv(DISOCCUPATION_FOR_NATION_path)

## Second Dataset: DISOCCUPATION_FOR_NATION

In [ ]:
DISOCCUPATION_FOR_NATION.head(5)

,DATAFLOW,LAST UPDATE,freq,age,unit,sex,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2016,6.5,NaN,NaN
1,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2017,5.9,NaN,NaN
2,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2018,5.2,NaN,NaN
3,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2019,4.8,NaN,NaN
4,ESTAT:UNE_RT_A$DEFAULTVIEW(1.0),11/06/26 23:00:00,Annual,From 15 to 74 years,Percentage of population in the labour force,Total,Austria,2020,6.0,NaN,NaN

In [ ]:
DISOCCUPATION_FOR_NATION.info()

<class 'pandas.DataFrame'>
RangeIndex: 1110 entries, 0 to 1109
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATAFLOW     1110 non-null   str
 1   LAST UPDATE  1110 non-null   str
 2   freq         1110 non-null   str
 3   age          1110 non-null   str
 4   unit         1110 non-null   str
 5   sex          1110 non-null   str
 6   geo          1110 non-null   str
 7   TIME_PERIOD  1110 non-null   int64
 8   OBS_VALUE    1110 non-null   float64
 9   OBS_FLAG     72 non-null     str
 10  CONF_STATUS  0 non-null      float64
dtypes: float64(2), int64(1), str(8)
memory usage: 95.5 KB

In [ ]:
DISOCCUPATION_FOR_NATION.shape

(1110, 11)

In [ ]:
DISOCCUPATION_FOR_NATION.isna().sum()

DATAFLOW          0
LAST UPDATE       0
freq              0
age               0
unit              0
sex               0
geo               0
TIME_PERIOD       0
OBS_VALUE         0
OBS_FLAG       1038
CONF_STATUS    1110
dtype: int64

In [ ]:
DISOCCUPATION_FOR_NATION.nunique()

DATAFLOW         1
LAST UPDATE      1
freq             1
age              1
unit             3
sex              1
geo             38
TIME_PERIOD     10
OBS_VALUE      418
OBS_FLAG         3
CONF_STATUS      0
dtype: int64

Like i see from the .nunique and the .isna().sum() preliminary analysis, there a lot of columns without significat information, like dataflow, last update, freq, sex, age, anc CONF_STATUS. <br>
So i'm going to drop that colums, but remembering that age is between 15 and 74, and in the dataset there is no difference between the sexes.

In [ ]:
DISOCCUPATION_FOR_NATION["age"].value_counts()

age
From 15 to 74 years    1110
Name: count, dtype: int64

In [ ]:
DISOCCUPATION_FOR_NATION= DISOCCUPATION_FOR_NATION.drop(["DATAFLOW", "LAST UPDATE", "freq", "age", "sex", "CONF_STATUS"],axis=1)

In [ ]:
DISOCCUPATION_FOR_NATION.head(3)

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG
0,Percentage of population in the labour force,Austria,2016,6.5,NaN
1,Percentage of population in the labour force,Austria,2017,5.9,NaN
2,Percentage of population in the labour force,Austria,2018,5.2,NaN

Now i'm going to analyze the columns separatel and looking in detail what type of data they containe.

In [ ]:
DISOCCUPATION_FOR_NATION["unit"].value_counts()

unit
Percentage of population in the labour force    370
Percentage of total population                  370
Thousand persons                                370
Name: count, dtype: int64

In [ ]:
DISOCCUPATION_FOR_NATION["geo"].value_counts()

geo
Austria                                      30
Belgium                                      30
Bulgaria                                     30
Switzerland                                  30
Cyprus                                       30
Czechia                                      30
Germany                                      30
Denmark                                      30
Euro area – 20 countries (2023-2025)         30
Euro area – 21 countries (from 2026)         30
Estonia                                      30
Greece                                       30
Spain                                        30
European Union - 27 countries (from 2020)    30
Finland                                      30
France                                       30
Croatia                                      30
Hungary                                      30
Ireland                                      30
Iceland                                      30
Italy                                        30
Lithuania                                    30
Luxembourg                                   30
Latvia                                       30
North Macedonia                              30
Malta                                        30
Netherlands                                  30
Norway                                       30
Poland                                       30
Portugal                                     30
Romania                                      30
Serbia                                       30
Sweden                                       30
Slovenia                                     30
Slovakia                                     30
Türkiye                                      30
Bosnia and Herzegovina                       15
Montenegro                                   15
Name: count, dtype: int64

In [ ]:
DISOCCUPATION_FOR_NATION[DISOCCUPATION_FOR_NATION["geo"].str.contains("Euro")]["geo"].value_counts()

geo
Euro area – 20 countries (2023-2025)         30
Euro area – 21 countries (from 2026)         30
European Union - 27 countries (from 2020)    30
Name: count, dtype: int64

In [ ]:
DISOCCUPATION_FOR_NATION["OBS_FLAG"].value_counts()

OBS_FLAG
b     42
d     27
bd     3
Name: count, dtype: int64

Before delving into the "OBS_FLAG" values, I isolate the "Percentage of population in the labour force," which is the standard metric for defining unemployment and the only one that allows for cross-country comparison. <br>
For the sake of clarity, I am specifying the meaning of the "OBS_FLAG":
- b: It changes the standard by which a variable is defined and observed over time, as a result of a single change or a combination of multiple changes at a given moment.
- d: The definition used deviates from the standard, with details in the metadata. 
- db: A break in the series and a differing definition. The three BD values ​​possess both characteristics.

In [ ]:
DISOCCUPATION_clean= DISOCCUPATION_FOR_NATION[DISOCCUPATION_FOR_NATION["unit"].isin(["Percentage of population in the labour force"])]

In [ ]:
DISOCCUPATION_clean.head(5)

,unit,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG
0,Percentage of population in the labour force,Austria,2016,6.5,NaN
1,Percentage of population in the labour force,Austria,2017,5.9,NaN
2,Percentage of population in the labour force,Austria,2018,5.2,NaN
3,Percentage of population in the labour force,Austria,2019,4.8,NaN
4,Percentage of population in the labour force,Austria,2020,6.0,NaN

The unit column is no longer necessary. i drop it. <br>
To preserve the information, I will add a clearer description of the OBS_VALUE column.

In [ ]:
DISOCCUPATION_clean["unit"].value_counts()

unit
Percentage of population in the labour force    370
Name: count, dtype: int64

In [ ]:
DISOCCUPATION_clean=DISOCCUPATION_clean.drop(["unit"], axis=1)

In [ ]:
DISOCCUPATION_clean["geo"].value_counts()

geo
Austria                                      10
Belgium                                      10
Bulgaria                                     10
Switzerland                                  10
Cyprus                                       10
Czechia                                      10
Germany                                      10
Denmark                                      10
Euro area – 20 countries (2023-2025)         10
Euro area – 21 countries (from 2026)         10
Estonia                                      10
Greece                                       10
Spain                                        10
European Union - 27 countries (from 2020)    10
Finland                                      10
France                                       10
Croatia                                      10
Hungary                                      10
Ireland                                      10
Iceland                                      10
Italy                                        10
Lithuania                                    10
Luxembourg                                   10
Latvia                                       10
North Macedonia                              10
Malta                                        10
Netherlands                                  10
Norway                                       10
Poland                                       10
Portugal                                     10
Romania                                      10
Serbia                                       10
Sweden                                       10
Slovenia                                     10
Slovakia                                     10
Türkiye                                      10
Bosnia and Herzegovina                        5
Montenegro                                    5
Name: count, dtype: int64

Now i will isolate in a new df the EU27-2020 value and create a new df with the EU 27 countries only.

In [ ]:
disoccupation_eu27 = DISOCCUPATION_clean[DISOCCUPATION_clean["geo"] == "EU27_2020"]

In [ ]:
disoccupation_eu27

Empty DataFrame
Columns: [geo, TIME_PERIOD, OBS_VALUE, OBS_FLAG]
Index: []

And concentrate the database only on the 27 EU countries

In [ ]:
list_27_names = [
    "Belgium", "Bulgaria", "Czechia", "Denmark", "Germany", "Estonia",
    "Ireland", "Greece", "Spain", "France", "Croatia", "Italy", "Cyprus",
    "Latvia", "Lithuania", "Luxembourg", "Hungary", "Malta", "Netherlands",
    "Austria", "Poland", "Portugal", "Romania", "Slovenia", "Slovakia",
    "Finland", "Sweden"
]
disoccupation_eu_countries = DISOCCUPATION_clean[DISOCCUPATION_clean["geo"].isin(list_27_names)].copy()

In [ ]:
disoccupation_eu_countries["geo"].nunique()

27

Now I'm creating a column with country codes, which will be useful for future joins and cross-analysis.

In [ ]:
country_to_code = {
    "Austria": "AT",
    "Belgium": "BE",
    "Bulgaria": "BG",
    "Croatia": "HR",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Denmark": "DK",
    "Estonia": "EE",
    "Finland": "FI",
    "France": "FR",
    "Germany": "DE",
    "Greece": "EL",
    "Hungary": "HU",
    "Ireland": "IE",
    "Italy": "IT",
    "Latvia": "LV",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Malta": "MT",
    "Netherlands": "NL",
    "Poland": "PL",
    "Portugal": "PT",
    "Romania": "RO",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Spain": "ES",
    "Sweden": "SE"
}
disoccupation_eu_countries["country_code"]=disoccupation_eu_countries["geo"].map(country_to_code)

In [ ]:
disoccupation_eu_countries

          geo  TIME_PERIOD  OBS_VALUE OBS_FLAG country_code
0     Austria         2016        6.5      NaN           AT
1     Austria         2017        5.9      NaN           AT
2     Austria         2018        5.2      NaN           AT
3     Austria         2019        4.8      NaN           AT
4     Austria         2020        6.0      NaN           AT
..        ...          ...        ...      ...          ...
355  Slovakia         2021        6.8      NaN           SK
356  Slovakia         2022        6.1      NaN           SK
357  Slovakia         2023        5.8      NaN           SK
358  Slovakia         2024        5.3      NaN           SK
359  Slovakia         2025        5.4      NaN           SK

[270 rows x 5 columns]

In [ ]:
disoccupation_eu_countries["OBS_FLAG"].value_counts()

OBS_FLAG
b     11
d      9
bd     1
Name: count, dtype: int64


Several flagged records remain; let's run a check to see for which countries and years the change occurred.

In [ ]:
disoccupation_eu_countries[disoccupation_eu_countries["OBS_FLAG"].notna()]["TIME_PERIOD"].value_counts()

TIME_PERIOD
2024    3
2023    3
2021    3
2017    2
2019    2
2022    2
2025    2
2018    2
2020    1
2016    1
Name: count, dtype: int64

In [ ]:
disoccupation_eu_countries[disoccupation_eu_countries["OBS_FLAG"].notna()]["geo"].value_counts()

geo
Spain       5
France      5
Denmark     3
Bulgaria    2
Belgium     1
Germany     1
Hungary     1
Ireland     1
Italy       1
Poland      1
Name: count, dtype: int64

To avoid misinterpreting the data in subsequent analyses, i decided to save a mini-dataframe containing information on the countries and the year in which a change was applied to the unemployment analysis metrics.

In [ ]:
unemployment_data_breaks=disoccupation_eu_countries[disoccupation_eu_countries["OBS_FLAG"].notna()].copy()

In [ ]:
unemployment_data_breaks

          geo  TIME_PERIOD  OBS_VALUE OBS_FLAG country_code
16    Belgium         2017        7.2        b           BE
28   Bulgaria         2019        5.2        b           BG
33   Bulgaria         2024        4.2        b           BG
69    Germany         2020        3.6        b           DE
75    Denmark         2016        6.0        b           DK
76    Denmark         2017        5.8        b           DK
82    Denmark         2023        5.1        b           DK
130     Spain         2021       14.9        d           ES
131     Spain         2022       13.0        d           ES
132     Spain         2023       12.2        d           ES
133     Spain         2024       11.4        d           ES
134     Spain         2025       10.5        d           ES
160    France         2021        7.9        d           FR
161    France         2022        7.3        d           FR
162    France         2023        7.3        d           FR
163    France         2024        7.4       bd           FR
164    France         2025        7.7        d           FR
177   Hungary         2018        3.6        b           HU
190   Ireland         2021        6.2        b           IE
207     Italy         2018       10.6        b           IT
293    Poland         2019        3.3        b           PL

From this dataframe, I will keep only country, country_code, OBS_FLAG and year. <br>
It will serve only to remind me which countries changed their measurement metrics, in which year and in what way.

In [ ]:
unemployment_data_breaks=unemployment_data_breaks.drop(["OBS_VALUE"], axis=1)
unemployment_data_breaks

          geo  TIME_PERIOD OBS_FLAG country_code
16    Belgium         2017        b           BE
28   Bulgaria         2019        b           BG
33   Bulgaria         2024        b           BG
69    Germany         2020        b           DE
75    Denmark         2016        b           DK
76    Denmark         2017        b           DK
82    Denmark         2023        b           DK
130     Spain         2021        d           ES
131     Spain         2022        d           ES
132     Spain         2023        d           ES
133     Spain         2024        d           ES
134     Spain         2025        d           ES
160    France         2021        d           FR
161    France         2022        d           FR
162    France         2023        d           FR
163    France         2024       bd           FR
164    France         2025        d           FR
177   Hungary         2018        b           HU
190   Ireland         2021        b           IE
207     Italy         2018        b           IT
293    Poland         2019        b           PL

In [ ]:
flag_labels = {
    "b": "break_in_series",
    "d": "definition_differs",
    "bd": "break_and_definition"
}
unemployment_data_breaks["OBS_FLAG"]=unemployment_data_breaks["OBS_FLAG"].replace(flag_labels)

In [ ]:
unemployment_data_breaks

          geo  TIME_PERIOD              OBS_FLAG country_code
16    Belgium         2017       break_in_series           BE
28   Bulgaria         2019       break_in_series           BG
33   Bulgaria         2024       break_in_series           BG
69    Germany         2020       break_in_series           DE
75    Denmark         2016       break_in_series           DK
76    Denmark         2017       break_in_series           DK
82    Denmark         2023       break_in_series           DK
130     Spain         2021    definition_differs           ES
131     Spain         2022    definition_differs           ES
132     Spain         2023    definition_differs           ES
133     Spain         2024    definition_differs           ES
134     Spain         2025    definition_differs           ES
160    France         2021    definition_differs           FR
161    France         2022    definition_differs           FR
162    France         2023    definition_differs           FR
163    France         2024  break_and_definition           FR
164    France         2025    definition_differs           FR
177   Hungary         2018       break_in_series           HU
190   Ireland         2021       break_in_series           IE
207     Italy         2018       break_in_series           IT
293    Poland         2019       break_in_series           PL

Now I can remove the "OBS_FLAG" col from the disoccupation_eu_countries DataFrame.

In [ ]:
disoccupation_eu_countries=disoccupation_eu_countries.drop(["OBS_FLAG"], axis=1)

In [ ]:
disoccupation_eu_countries

          geo  TIME_PERIOD  OBS_VALUE country_code
0     Austria         2016        6.5           AT
1     Austria         2017        5.9           AT
2     Austria         2018        5.2           AT
3     Austria         2019        4.8           AT
4     Austria         2020        6.0           AT
..        ...          ...        ...          ...
355  Slovakia         2021        6.8           SK
356  Slovakia         2022        6.1           SK
357  Slovakia         2023        5.8           SK
358  Slovakia         2024        5.3           SK
359  Slovakia         2025        5.4           SK

[270 rows x 4 columns]

 Now i rename the cols of the df, to be in line with GDP_EU_countries df done previously. <br>
 after that i reorder the col to make reading easier and save it in clean_data togheter with unemployment_data_breaks df.

In [ ]:
disoccupation_eu_countries=disoccupation_eu_countries.rename(columns={
     "OBS_VALUE": "unemployment_rate",
    "TIME_PERIOD": "year",
})

In [ ]:
col_order= ["country_code","geo","year","unemployment_rate"]
disoccupation_eu_countries=disoccupation_eu_countries[col_order]
disoccupation_eu_countries

    country_code       geo  year  unemployment_rate
0             AT   Austria  2016                6.5
1             AT   Austria  2017                5.9
2             AT   Austria  2018                5.2
3             AT   Austria  2019                4.8
4             AT   Austria  2020                6.0
..           ...       ...   ...                ...
355           SK  Slovakia  2021                6.8
356           SK  Slovakia  2022                6.1
357           SK  Slovakia  2023                5.8
358           SK  Slovakia  2024                5.3
359           SK  Slovakia  2025                5.4

[270 rows x 4 columns]

In [ ]:
disoccupation_eu_countries=disoccupation_eu_countries.rename(columns={"geo": "country"})
unemployment_data_breaks=unemployment_data_breaks.rename(columns={"geo": "country"})

In [ ]:
disoccupation_eu_countries.info()

<class 'pandas.DataFrame'>
Index: 270 entries, 0 to 359
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country_code       270 non-null    str
 1   country            270 non-null    str
 2   year               270 non-null    int64
 3   unemployment_rate  270 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 10.5 KB

In [ ]:
disoccupation_eu_countries.to_csv(Path.cwd().parent/"data/clean_data/disoccupation_eu_countries.csv", index= False)
unemployment_data_breaks.to_csv(Path.cwd().parent/"data/clean_data/unemployment_data_breaks.csv", index= False)

I create the database and save the cleaned DataFrame inside it.

In [ ]:
import sqlite3
conn = sqlite3.connect(Path.cwd().parent/"database/ue_market.db")

In [ ]:
disoccupation_eu_countries.to_sql("unemployment_ue", conn, if_exists="replace", index=False)
unemployment_data_breaks.to_sql("data_breaks_ue", conn, if_exists= "replace", index= False)

21