#  GDP DIAGNOSTIC EXPLORATION
In this notebook I am proceeding to conduct a diagnostic analysis of the GDP dataset and preparing it for next analysis.

In [41]:
import pandas as pd
from pathlib import Path

In [42]:
GDP_FOR_NATION_path= Path.cwd().parent/"data/raw_data/GDP_for_nation.csv"

In [43]:
GDP_FOR_NATION= pd.read_csv(GDP_FOR_NATION_path)

## First Dataset: GDP_FOR_NATION

In [44]:
GDP_FOR_NATION.head(5)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,unit,Unit of measure,na_item,National accounts indicator (ESA 2010),geo,Geopolitical entity (reporting),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2016,NaN,10420.1,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2017,NaN,10762.2,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2018,NaN,11157.3,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2019,NaN,11387.4,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:NAMA_10_GDP$DEFAULTVIEW(1.0),Gross domestic product (GDP) and main componen...,A,Annual,CLV10_MEUR,"Chain linked volumes (2010), million euro",B1GQ,Gross domestic product at market prices,AL,Albania,2020,NaN,11010.1,NaN,NaN,NaN,NaN,NaN

In [45]:
GDP_FOR_NATION.info()

<class 'pandas.DataFrame'>
RangeIndex: 1345 entries, 0 to 1344
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   STRUCTURE                               1345 non-null   str
 1   STRUCTURE_ID                            1345 non-null   str
 2   STRUCTURE_NAME                          1345 non-null   str
 3   freq                                    1345 non-null   str
 4   Time frequency                          1345 non-null   str
 5   unit                                    1345 non-null   str
 6   Unit of measure                         1345 non-null   str
 7   na_item                                 1345 non-null   str
 8   National accounts indicator (ESA 2010)  1345 non-null   str
 9   geo                                     1345 non-null   str
 10  Geopolitical entity (reporting)         1345 non-null   str
 11  TIME_PERIOD                             1345 non-null   int64
 12  Time                                    0 non-null      float64
 13  OBS_VALUE                               1345 non-null   float64
 14  Observation value                       0 non-null      float64
 15  OBS_FLAG                                102 non-null    str
 16  Observation status (Flag) V2 structure  102 non-null    str
 17  CONF_STATUS                             0 non-null      float64
 18  Confidentiality status (flag)           0 non-null      float64
dtypes: float64(5), int64(1), str(13)
memory usage: 199.8 KB

In [46]:
GDP_FOR_NATION.shape

(1345, 19)

In [47]:
GDP_FOR_NATION.isna().sum()

STRUCTURE                                    0
STRUCTURE_ID                                 0
STRUCTURE_NAME                               0
freq                                         0
Time frequency                               0
unit                                         0
Unit of measure                              0
na_item                                      0
National accounts indicator (ESA 2010)       0
geo                                          0
Geopolitical entity (reporting)              0
TIME_PERIOD                                  0
Time                                      1345
OBS_VALUE                                    0
Observation value                         1345
OBS_FLAG                                  1243
Observation status (Flag) V2 structure    1243
CONF_STATUS                               1345
Confidentiality status (flag)             1345
dtype: int64

In [48]:
GDP_FOR_NATION.nunique()

STRUCTURE                                    1
STRUCTURE_ID                                 1
STRUCTURE_NAME                               1
freq                                         1
Time frequency                               1
unit                                         3
Unit of measure                              3
na_item                                      1
National accounts indicator (ESA 2010)       1
geo                                         47
Geopolitical entity (reporting)             47
TIME_PERIOD                                 10
Time                                         0
OBS_VALUE                                 1312
Observation value                            0
OBS_FLAG                                     2
Observation status (Flag) V2 structure       2
CONF_STATUS                                  0
Confidentiality status (flag)                0
dtype: int64

Now that I have a fairly clear idea of ​​the column contents, I am proceeding to drop those containing data of little relevance (e.g., all NaNs or a single, uninformative value).

In [49]:
GDP_FOR_NATION= GDP_FOR_NATION.drop(["STRUCTURE",
"STRUCTURE_ID",
"STRUCTURE_NAME",
"freq",
"Time frequency",
"na_item",
"National accounts indicator (ESA 2010)",
"Time",
"Observation value",
"CONF_STATUS",
"Confidentiality status (flag)"], axis=1, )

In [ ]:
GDP_FOR_NATION

,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE,OBS_FLAG,Observation status (Flag) V2 structure
0,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2016,10420.1,NaN,NaN
1,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2017,10762.2,NaN,NaN
2,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2018,11157.3,NaN,NaN
3,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2019,11387.4,NaN,NaN
4,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2020,11010.1,NaN,NaN
...,...,...,...,...,...,...,...,...
1340,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2021,7957.9,NaN,NaN
1341,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2022,8895.7,NaN,NaN
1342,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2023,9680.1,NaN,NaN
1343,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2024,10350.4,NaN,NaN
1344,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2025,11026.3,p,provisional

In [51]:
GDP_FOR_NATION["Unit of measure"].value_counts()

Unit of measure
Current prices, million euro                 461
Chain linked volumes (2010), million euro    442
Chain linked volumes, index 2010=100         442
Name: count, dtype: int64

For the next analysis i will keep only the current prices in million euro and the chain linked volumes in million euro. i will eliminate the third one.

In [52]:
GDP_clean= GDP_FOR_NATION[GDP_FOR_NATION["Unit of measure"].isin(["Current prices, million euro", "Chain linked volumes (2010), million euro"])]

In [53]:
GDP_clean.head(3)

,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE,OBS_FLAG,Observation status (Flag) V2 structure
0,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2016,10420.1,NaN,NaN
1,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2017,10762.2,NaN,NaN
2,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2018,11157.3,NaN,NaN

In [54]:
GDP_clean["OBS_FLAG"].value_counts()

OBS_FLAG
p    64
e     5
Name: count, dtype: int64

In [55]:
GDP_clean[GDP_clean["OBS_FLAG"] == "p"]["TIME_PERIOD"].value_counts()

TIME_PERIOD
2025    29
2024    24
2023     9
2022     2
Name: count, dtype: int64

In [56]:
GDP_clean[GDP_clean["OBS_FLAG"] == "e"]["TIME_PERIOD"].value_counts()

TIME_PERIOD
2025    4
2024    1
Name: count, dtype: int64

In the columns"OBS_FLAG", the "p" datas are proviprovisional, while the "e" datas are estimated.<br>
Before dropping this col i want to check the eventually duplicated elements.<br>
the NaN values are the confimerd one.

In [57]:
GDP_clean[GDP_clean.duplicated(subset=["geo", "unit", "TIME_PERIOD"], keep=False)].count()

unit                                      0
Unit of measure                           0
geo                                       0
Geopolitical entity (reporting)           0
TIME_PERIOD                               0
OBS_VALUE                                 0
OBS_FLAG                                  0
Observation status (Flag) V2 structure    0
dtype: int64

There aren't duplicate for geo, unit and time period, we can eliminate also the OBS_FLAG.

In [58]:
GDP_clean=GDP_clean.drop(["OBS_FLAG"], axis=1)

In [59]:
GDP_clean

,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE,Observation status (Flag) V2 structure
0,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2016,10420.1,NaN
1,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2017,10762.2,NaN
2,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2018,11157.3,NaN
3,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2019,11387.4,NaN
4,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2020,11010.1,NaN
...,...,...,...,...,...,...,...
1340,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2021,7957.9,NaN
1341,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2022,8895.7,NaN
1342,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2023,9680.1,NaN
1343,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2024,10350.4,NaN
1344,CP_MEUR,"Current prices, million euro",XK,Kosovo*,2025,11026.3,provisional

In [60]:
GDP_clean["Observation status (Flag) V2 structure"].value_counts()

Observation status (Flag) V2 structure
provisional    64
estimated       5
Name: count, dtype: int64

In the previous OBS_FLAG analysis i confirmed that there aren't duplicate in the dataset, so we can eliminate also the "Observation status (Flag) V2 structure"

In [61]:
GDP_clean.drop(["Observation status (Flag) V2 structure"], axis=1, inplace=True)

In [62]:
GDP_clean.isna().sum()

unit                               0
Unit of measure                    0
geo                                0
Geopolitical entity (reporting)    0
TIME_PERIOD                        0
OBS_VALUE                          0
dtype: int64

In [63]:
GDP_clean.head(5)

,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
0,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2016,10420.1
1,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2017,10762.2
2,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2018,11157.3
3,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2019,11387.4
4,CLV10_MEUR,"Chain linked volumes (2010), million euro",AL,Albania,2020,11010.1

In [64]:
GDP_clean.info()

<class 'pandas.DataFrame'>
Index: 903 entries, 0 to 1344
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   unit                             903 non-null    str
 1   Unit of measure                  903 non-null    str
 2   geo                              903 non-null    str
 3   Geopolitical entity (reporting)  903 non-null    str
 4   TIME_PERIOD                      903 non-null    int64
 5   OBS_VALUE                        903 non-null    float64
dtypes: float64(1), int64(1), str(4)
memory usage: 49.4 KB

In [65]:
GDP_clean["Geopolitical entity (reporting)"].value_counts()

Geopolitical entity (reporting)
Austria                                                                                                                     20
Bosnia and Herzegovina                                                                                                      20
Belgium                                                                                                                     20
Bulgaria                                                                                                                    20
Switzerland                                                                                                                 20
Cyprus                                                                                                                      20
Czechia                                                                                                                     20
Germany                                                                                                                     20
Denmark                                                                                                                     20
Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015, EA20-2023, EA21-2026)    20
Euro area - 12 countries (2001-2006)                                                                                        20
Euro area - 19 countries  (2015-2022)                                                                                       20
Euro area – 20 countries (2023-2025)                                                                                        20
Euro area – 21 countries (from 2026)                                                                                        20
Estonia                                                                                                                     20
Greece                                                                                                                      20
Spain                                                                                                                       20
European Union - 27 countries (from 2020)                                                                                   20
Finland                                                                                                                     20
France                                                                                                                      20
Croatia                                                                                                                     20
Hungary                                                                                                                     20
Ireland                                                                                                                     20
Iceland                                                                                                                     20
Italy                                                                                                                       20
Lithuania                                                                                                                   20
Luxembourg                                                                                                                  20
Latvia                                                                                                                      20
Montenegro                                                                                                                  20
North Macedonia                                                                                                             20
Malta                                                                                                                       20
Netherlands                                                                                                                 20
Norway                                                                                                                      20
Poland                                                                                                                      20
Portugal                                                                                                                    20
Romania                                                                                                                     20
Serbia                                                                                                                      20
Sweden                                                                                                                      20
Slovenia                                                                                                                    20
Slovakia                                                                                                                    20
Türkiye                                                                                                                     20
Kosovo*                                                                                                                     20
Albania                                                                                                                     18
Ukraine                                                                                                                     18
Moldova                                                                                                                     10
Liechtenstein                                                                                                                9
United Kingdom                                                                                                               8
Name: count, dtype: int64

In [66]:
GDP_clean[GDP_clean["Geopolitical entity (reporting)"].str.contains("Euro")]["Geopolitical entity (reporting)"].value_counts()

Geopolitical entity (reporting)
Euro area (EA11-1999, EA12-2001, EA13-2007, EA15-2008, EA16-2009, EA17-2011, EA18-2014, EA19-2015, EA20-2023, EA21-2026)    20
Euro area - 12 countries (2001-2006)                                                                                        20
Euro area - 19 countries  (2015-2022)                                                                                       20
Euro area – 20 countries (2023-2025)                                                                                        20
Euro area – 21 countries (from 2026)                                                                                        20
European Union - 27 countries (from 2020)                                                                                   20
Name: count, dtype: int64

In [67]:
GDP_clean["geo"].value_counts()

geo
AT           20
BA           20
BE           20
BG           20
CH           20
CY           20
CZ           20
DE           20
DK           20
EA           20
EA12         20
EA19         20
EA20         20
EA21         20
EE           20
EL           20
ES           20
EU27_2020    20
FI           20
FR           20
HR           20
HU           20
IE           20
IS           20
IT           20
LT           20
LU           20
LV           20
ME           20
MK           20
MT           20
NL           20
NO           20
PL           20
PT           20
RO           20
RS           20
SE           20
SI           20
SK           20
TR           20
XK           20
AL           18
UA           18
MD           10
LI            9
UK            8
Name: count, dtype: int64

In [68]:
GDP_clean[(GDP_clean["geo"].str.contains("EA")) | (GDP_clean["geo"].str.contains("EU"))]["geo"].value_counts()

geo
EA           20
EA12         20
EA19         20
EA20         20
EA21         20
EU27_2020    20
Name: count, dtype: int64

I control what type of aggregators are inside the db. For added certainty, I checked both "geo" and ""Geopolitical entity (reporting)". <br>
Both analysis return 6 elements with 20 items. <br>
Now i will isolate in a new df the EU27-2020 value and create a new df with the EU 27 countries only.

In [69]:
gdp_eu27 = GDP_clean[GDP_clean["geo"] == "EU27_2020"]

In [70]:
gdp_eu27

,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
179,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2016,11835289.3
180,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2017,12168293.7
181,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2018,12417209.6
182,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2019,12650096.3
183,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2020,11946516.8
184,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2021,12705281.8
185,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2022,13156106.1
186,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2023,13215827.0
187,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2024,13370115.9
188,CLV10_MEUR,"Chain linked volumes (2010), million euro",EU27_2020,European Union - 27 countries (from 2020),2025,13575674.0
1063,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2016,12638272.4
1064,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2017,13169370.9
1065,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2018,13628646.5
1066,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2019,14122772.4
1067,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2020,13578815.3
1068,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2021,14792278.2
1069,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2022,16170154.5
1070,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2023,17264212.6
1071,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2024,18042085.3
1072,CP_MEUR,"Current prices, million euro",EU27_2020,European Union - 27 countries (from 2020),2025,18831892.5

In [71]:
list_27=["AT","BE","BG","CY","CZ","DE","DK","EE","EL","ES","FI","FR","HR","HU","IE","IT","LT","LU","LV","MT","NL","PL","PT","RO","SE","SI","SK"]
gdp_eu_countries = GDP_clean[GDP_clean["geo"].isin(list_27)].copy()

In [72]:
gdp_eu_countries

,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
9,CLV10_MEUR,"Chain linked volumes (2010), million euro",AT,Austria,2016,316647.9
10,CLV10_MEUR,"Chain linked volumes (2010), million euro",AT,Austria,2017,323842.9
11,CLV10_MEUR,"Chain linked volumes (2010), million euro",AT,Austria,2018,331887.9
12,CLV10_MEUR,"Chain linked volumes (2010), million euro",AT,Austria,2019,337712.4
13,CLV10_MEUR,"Chain linked volumes (2010), million euro",AT,Austria,2020,316374.9
...,...,...,...,...,...,...
1307,CP_MEUR,"Current prices, million euro",SK,Slovakia,2021,101891.6
1308,CP_MEUR,"Current prices, million euro",SK,Slovakia,2022,109959.8
1309,CP_MEUR,"Current prices, million euro",SK,Slovakia,2023,123538.7
1310,CP_MEUR,"Current prices, million euro",SK,Slovakia,2024,130207.5
1311,CP_MEUR,"Current prices, million euro",SK,Slovakia,2025,136754.3

In [73]:
gdp_eu_countries["geo"].value_counts()

geo
AT    20
BE    20
BG    20
CY    20
CZ    20
DE    20
DK    20
EE    20
EL    20
ES    20
FI    20
FR    20
HR    20
HU    20
IE    20
IT    20
LT    20
LU    20
LV    20
MT    20
NL    20
PL    20
PT    20
RO    20
SE    20
SI    20
SK    20
Name: count, dtype: int64

Finally:

- Rename the 'unit' elements to clarify that one value accounts for inflation while the other does not, thereby eliminating the 'unit of measure' column, which only creates redundancy;
- Rename columns containing spaces that complicate SQL analysis;
- Assign the unit of measure (e.g., million_euro) directly to OBS_VALUE so the information is not lost.

In [74]:
#Rename "unit" element.
gdp_eu_countries["unit"]=gdp_eu_countries["unit"].replace({"CP_MEUR": "nominal", "CLV10_MEUR": "real"})

In [75]:
gdp_eu_countries

,unit,Unit of measure,geo,Geopolitical entity (reporting),TIME_PERIOD,OBS_VALUE
9,real,"Chain linked volumes (2010), million euro",AT,Austria,2016,316647.9
10,real,"Chain linked volumes (2010), million euro",AT,Austria,2017,323842.9
11,real,"Chain linked volumes (2010), million euro",AT,Austria,2018,331887.9
12,real,"Chain linked volumes (2010), million euro",AT,Austria,2019,337712.4
13,real,"Chain linked volumes (2010), million euro",AT,Austria,2020,316374.9
...,...,...,...,...,...,...
1307,nominal,"Current prices, million euro",SK,Slovakia,2021,101891.6
1308,nominal,"Current prices, million euro",SK,Slovakia,2022,109959.8
1309,nominal,"Current prices, million euro",SK,Slovakia,2023,123538.7
1310,nominal,"Current prices, million euro",SK,Slovakia,2024,130207.5
1311,nominal,"Current prices, million euro",SK,Slovakia,2025,136754.3

In [76]:
# Rename columns and drop "Unit of measure"
gdp_eu_countries=gdp_eu_countries.rename(columns={
    "OBS_VALUE": "gdp_meur",
    "TIME_PERIOD": "year",
    "geo": "country_code",
    "Geopolitical entity (reporting)":"country"
}).drop("Unit of measure", axis=1)

In [77]:
gdp_eu_countries.head(3)

    unit country_code  country  year  gdp_meur
9   real           AT  Austria  2016  316647.9
10  real           AT  Austria  2017  323842.9
11  real           AT  Austria  2018  331887.9

In [78]:
gdp_eu_countries.to_csv(Path.cwd().parent/"data/clean_data/GDP_EU_countries.csv", index= False)

I create the database and save the cleaned DataFrame inside it.

In [79]:
import sqlite3
conn = sqlite3.connect(Path.cwd().parent/"database/ue_market.db")

In [80]:
gdp_eu_countries.to_sql("gdp_ue", conn, if_exists="replace", index=False)

540