## Database exploration.
In this section i analyze the df, if all datasets are correctly uploaded and if they contains the correct cols.

In [1]:
import sqlite3
from pathlib import Path
import pandas as pd

In [2]:
conn = sqlite3.connect(Path.cwd().parent/"database/ue_market.db")

In [3]:
pd.read_sql("SELECT name FROM sqlite_master WHERE   type= 'table'", conn)

              name
0   trade_category
1      trade_total
2  unemployment_ue
3   data_breaks_ue
4           gdp_ue

In [4]:
pd.read_sql("""
SELECT *
FROM unemployment_ue
limit 5
""", conn)

  country_code  country  year  unemployment_rate
0           AT  Austria  2016                6.5
1           AT  Austria  2017                5.9
2           AT  Austria  2018                5.2
3           AT  Austria  2019                4.8
4           AT  Austria  2020                6.0

In [5]:
pd.read_sql("""
SELECT *
FROM gdp_ue
limit 5
""", conn)

   unit country_code  country  year  gdp_meur
0  real           AT  Austria  2016  316647.9
1  real           AT  Austria  2017  323842.9
2  real           AT  Austria  2018  331887.9
3  real           AT  Austria  2019  337712.4
4  real           AT  Austria  2020  316374.9

In [6]:
pd.read_sql("""
            SELECT *
            FROM trade_total
            LIMIT 5
            """, conn)

  country_code product_code product_description  year indic_et  value_meur
0           AT        TOTAL               total  2002  balance       395.4
1           BE        TOTAL               total  2002  balance     18841.3
2           BG        TOTAL               total  2002  balance     -2348.4
3           CY        TOTAL               total  2002  balance     -3453.5
4           CZ        TOTAL               total  2002  balance     -2289.0

In [7]:
pd.read_sql("""
            SELECT *
            FROM trade_category
            LIMIT 5
            """, conn)

  country_code product_code  product_description  year indic_et  value_meur
0           AT      SITC0_1  food_drinks_tobacco  2002  balance      -504.7
1           BE      SITC0_1  food_drinks_tobacco  2002  balance      2625.4
2           BG      SITC0_1  food_drinks_tobacco  2002  balance       210.9
3           CY      SITC0_1  food_drinks_tobacco  2002  balance      -302.5
4           CZ      SITC0_1  food_drinks_tobacco  2002  balance      -688.3

All the DataFrames load correctly and contain all the required columns. The column names are correct for future joins.