## Dimension exploration.
In this section i analyze the cols that i can join in the next queries, the date boundaries that i have and the dimensions of all df.

In [1]:
import sqlite3
from pathlib import Path
import pandas as pd

conn = sqlite3.connect(Path.cwd().parent/"database/ue_market.db")
pd.read_sql("SELECT name FROM sqlite_master WHERE   type= 'table'", conn)

              name
0   trade_category
1      trade_total
2  unemployment_ue
3   data_breaks_ue
4           gdp_ue

In [2]:
pd.read_sql("""
            SELECT 
            COUNT(DISTINCT country_code) AS n_countries,
            COUNT(DISTINCT year) AS n_years,
            MIN(year) AS first_year,
            MAX(year) AS last_year,
            COUNT(*) AS total_rows
            FROM unemployment_ue""",
            conn)

   n_countries  n_years  first_year  last_year  total_rows
0           27       10        2016       2025         270

In [3]:
pd.read_sql("""
            SELECT 
            COUNT(DISTINCT country_code) AS n_countries,
            COUNT(DISTINCT year) AS n_years,
            COUNT(DISTINCT unit) AS n_units,
            MIN(year) AS first_year,
            MAX(year) AS last_year,
            COUNT(*) AS total_rows
            FROM gdp_ue""",
            conn)

   n_countries  n_years  n_units  first_year  last_year  total_rows
0           27       10        2        2016       2025         540

In [4]:
pd.read_sql("""
            SELECT 
            COUNT(DISTINCT country_code) AS n_countries,
            COUNT(DISTINCT year) AS n_years,
            COUNT(DISTINCT indic_et) AS indics,
            MIN(year) AS first_year,
            MAX(year) AS last_year,
            COUNT(*) AS total_rows
            FROM trade_total""",
            conn)

   n_countries  n_years  indics  first_year  last_year  total_rows
0           27       24       3        2002       2025        1944

In [5]:
pd.read_sql("""
            SELECT 
            COUNT(DISTINCT country_code) AS n_countries,
            COUNT(DISTINCT year) AS n_years,
            COUNT(DISTINCT indic_et) AS indics,
            COUNT(DISTINCT product_code) AS n_products,
            MIN(year) AS first_year,
            MAX(year) AS last_year,
            COUNT(*) AS total_rows
            FROM trade_category""",
            conn)

   n_countries  n_years  indics  n_products  first_year  last_year  total_rows
0           27       24       3           7        2002       2025       13608

The number of countries is indeed 27; the "gdp_ue" dataframe has twice as many rows as the "unemployment_ue" dataframe. This is because "gdp_ue" contains two units in the col: one for real values ​​and one for nominal values. <br>
The "trade_category" and "trade_total" dataframes contain historical data starting from 2002, unlike "gdp_ue" and "unemployment_ue". <br>
For the analysis of the 2008 crisis, I will use only the latter dataframes, given that the others lack data for those years